matsko lab 33
NSU-FIT-Operating-Systems/20205-POSIX-Threads pull request #16
Opened 2022-12-21 17:05 UTC by AleksandrMatsko

2022-12-22 12:16 UTC, AleksandrMatsko commented
прокси проходит тесты Александра Иванова из группы 20201

2022-12-22 23:22 UTC, brzheutskii requested changes

2022-12-22 23:22 UTC, brzheutskii commented on matsko/33_proxy_with_thread_pool/task_queue.c
> +        return 0;
Откровенно говоря не понимаю зачем вам тут два мютекса. 
У вас тут три блока, но второй и третий блок (ситуация когда tail=head и и они не равные нулю и ситуация когда tail!= head) одинаковые по коду (просто замените во втором блоке queue->head на queue-tail так как они равны и будет одинаковый код, за исколючением захвата мютексов), в первом блоке у вас избыточно условие проверки что tail и head равны (если один из них null то они неизбежно равны), и, что самое важное, почти во всех случаях вы сначала захватываете два мютекса, а потом отпускаете два мютекса. Раз все так, то мне кажется логичнее оставить один мютекс просто на очередь. 
Мне не очень нравится этот подход и я бы предпочел использовать atomic функции для сравнений и замен, но уж хотя бы с мютексами давайте не будет делать ситуацию избыточной.

2022-12-22 23:22 UTC, brzheutskii commented on matsko/33_proxy_with_thread_pool/proxy.c
> +                handled = true;
У вас тут выше 4 кода блока практически строчка в строчку одинаковые, давайте не будем дублировать код, вынесите это в функцию пожалуйста.

2022-12-22 23:22 UTC, brzheutskii commented on matsko/33_proxy_with_thread_pool/proxy.c
> +            err = pthread_cond_wait(&cond, &tasks_counter_mutex);
Если я правильно понял, вот эта часть кода притормаживает main поток с poll пока не выполняться все задачи из очереди. Делать так нехорошо, потому что это скорее всего будет оказывать влияние на скорость подключения клиента как минимум (это формальное нарушение правила 13), плюс у вас и все остальные операции могут стоять в ожидании. Так как у вас non_block соединения это не дает такой критичный эффект, но тем не менее вам поидее нехорошо ограничевать poll задержками, иначе вы теряете его мощь, а именно быстрее реагирование на событие системы.

2022-12-22 23:30 UTC, brzheutskii commented
И еще общие коментрии
- снова какая то странная тема с нагрузкой на процессор, причем если размер пула сделать по больше, например 10, то в воркер тредах там все становится близким к желаемому (менее 10%, чащей даже менее 5% CPU), но вот main все равно порядка 50%, в пиках до 60%. Если сделать пул минимальный (1 то есть), то там ситуация одинаково плохая во всех потоках, мне удалось поймать под 70% CPU. Это все довольно многовато, учитывая опять же у основную работу с ожидаением у вас делает poll, а все потоки вы создаете сразу в начале. Добиться значений чистого poll у нас тут наврядли получится, так как синхронизации есть, но поидее должно быть близко.
- в целом ваш подход с распределением по потокам именно конкретных функций валиден и довольно лаконичен в вашем коде, по сути там появилась небольшая обертка над функциями обмена данными, очередь и синхронизация в pollfd и cach записей. Есть так же другой подход - это засунуть в потоки вообще весь цикл с poll из задачи 31 , сделать локальные для потоков poll_fd без синхронизации или общий синхронизаций и сделать синхронизацию по сache. Пишу вам про такую схему, потому как в ней обычно нет доп ожиданий в циклe с poll, так как вы делаете и так все что можете в рамках потока, плюс вы потенциально получаете бонус к производительности изза более частого вызова poll в среднем (хотя это конечно дискуссионный вопрос).

2022-12-25 16:37 UTC, AleksandrMatsko commented
> И еще общие коментрии
> 
> * снова какая то странная тема с нагрузкой на процессор, причем если размер пула сделать по больше, например 10, то в воркер тредах там все становится близким к желаемому (менее 10%, чащей даже менее 5% CPU), но вот main все равно порядка 50%, в пиках до 60%. Если сделать пул минимальный (1 то есть), то там ситуация одинаково плохая во всех потоках, мне удалось поймать под 70% CPU. Это все довольно многовато, учитывая опять же у основную работу с ожидаением у вас делает poll, а все потоки вы создаете сразу в начале. Добиться значений чистого poll у нас тут наврядли получится, так как синхронизации есть, но поидее должно быть близко.
> * в целом ваш подход с распределением по потокам именно конкретных функций валиден и довольно лаконичен в вашем коде, по сути там появилась небольшая обертка над функциями обмена данными, очередь и синхронизация в pollfd и cach записей. Есть так же другой подход - это засунуть в потоки вообще весь цикл с poll из задачи 31 , сделать локальные для потоков poll_fd без синхронизации или общий синхронизаций и сделать синхронизацию по сache. Пишу вам про такую схему, потому как в ней обычно нет доп ожиданий в циклe с poll, так как вы делаете и так все что можете в рамках потока, плюс вы потенциально получаете бонус к производительности изза более частого вызова poll в среднем (хотя это конечно дискуссионный вопрос).

Пересмотрел архитектуру, теперь у каждого потока в пуле свой массив для poll, свои клиенты и сервера. Main поток занимается приёмом клиентов и остановкой.

2022-12-25 21:18 UTC, brzheutskii commented
> Пересмотрел архитектуру, теперь у каждого потока в пуле свой массив для poll, свои клиенты и сервера. Main поток занимается приёмом клиентов и остановкой. При подключении большого числа клиентов разом нагрузка может возрастать, т.к. тогда фактически main поток крутится в цикле и уведомляет другие потоки.

Звучит здорово, только потестить неудалось, у вас там в коде файла `task_queue.h` мердж кофнликт не разрешенный закоммичен, ну и из-за этого не собирается. Поправьте пожлауйста, чтоб позапускать. Ну и коменты https://github.com/NSU-FIT-Operating-Systems/20205-POSIX-Threads/pull/16#discussion_r1055913907 , https://github.com/NSU-FIT-Operating-Systems/20205-POSIX-Threads/pull/16#discussion_r1055918359 и https://github.com/NSU-FIT-Operating-Systems/20205-POSIX-Threads/pull/16#discussion_r1055922373 не забудьте

2022-12-27 22:35 UTC, brzheutskii approved these changes

2022-12-27 22:35 UTC, brzheutskii commented
По коду все хорошо, по логике мы все обсудили. Принимаю пул реквест

2022-12-27 22:35 UTC, merged