Lab_16
NSU-FIT-Operating-Systems/20205-POSIX-Threads pull request #17
Opened 2022-12-22 06:26 UTC by punch-bob

2022-12-22 17:23 UTC, ksilobait commented
Не стоить коммитить в репозиторий скомпилированные файлы - их можно сгенерировать имея исходные файлы. Кроме того просто получить ситуацию, в которой исходные файлы более новой версии, а скомпилированные не обновлены (особенно после мержей)

2022-12-22 17:24 UTC, ksilobait commented
На сервере программа не компилируется - некоторые библиотеки не подключены
 `error: ‘O_CREAT’ undeclared (first use in this function)`
`error: implicit declaration of function ‘wait’`

2022-12-22 17:31 UTC, ksilobait commented
Так как git поддерживает вложенные ветки, лучше называть ветку с разделителем `/`: rybalko/lab_16 - в визуальных отображениях для git будет видна структура папок для веток

2022-12-25 21:24 UTC, brzheutskii requested changes

2022-12-25 21:24 UTC, brzheutskii commented on rybalko/16/lab_16.c
> +    CloseAllSem();
Вы там выше в случае аварийной ситуации вызываете unlink для семафоров, а тут вроде как уже нормальная ситуация, а unlink не вызвали, выглядит не логично. Давайте или обсудим на паре почему так или поправим

2022-12-28 17:10 UTC, merged